name: Publish to GitHub Package Registry

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '8.x', '10.x', '12.x' ]

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Node.js ${{ matrix.node }}
      uses: actions/setup-node@master
      with:
        registry-url: https://npm.pkg.github.com/
        node-version: ${{ matrix.node }}
        scope: '@scottjwalter'
    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm test      
    - name: publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        npm run deploy
